#!/bin/bash

#DIR=/home/toe/cpu2006/benchspec/CPU2006/401.bzip2/exe
#BIN=bzip2_base.i386-m32-gcc44-3.bin
#LOGDIR=tests/log/$1
LOGDIR=data

mkdir -p $LOGDIR
# [ -e $LOGDIR/pipe ] || mkfifo $LOGDIR/pipe

# date > $LOGDIR/time.start

echo > $LOGDIR/"$1"_sum
for size in 0 50 100; do
    echo -n "S$size " >> $LOGDIR/"$1"_sum
    for core in 16 64 256; do
	for depth in 16 64 256; do
	    luajit mrb_share_L1.lua -c$core -s$size -d$depth < $1.log > $LOGDIR/$1_regsync_c"$core"_s"$size"_d"$depth"_log
	    regsyn_pull=$(tail -n1 $LOGDIR/$1_regsync_c"$core"_s"$size"_d"$depth"_log | cut -f3 -d:)
	    echo -n "& $regsyn_pull " >> $LOGDIR/"$1"_sum
	    luajit mrb_share_L1.lua -a -c$core -s$size -d$depth < $1.log > $LOGDIR/$1_regsync_c"$core"_s"$size"_d"$depth"_a_log
	done
    done    
    echo "\\\\" >> $LOGDIR/"$1"_sum
done

# #valgrind --tool=lackey --log-file=$LOGDIR/pipe --trace-mem=yes --trace-superblocks=yes $@

# | split -a 4 -b 512M - $LOGDIR/log

#date > $LOGDIR/time.end
